kind: Service
apiVersion: v1
metadata:
  name: server1
spec:
  selector:
    app: server1
  ports:
    - protocol: TCP
      port: 8585
      nodePort: 30083
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server1
spec:
  selector:
    matchLabels:
      app: server1
  replicas: 3
  template:
    metadata:
      labels:
        app: server1
    spec:
      containers:
        - name: server1
          image: server1:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8585
